version: "3.8"
services:
  frontend:
    image: quangtt91/frontend:latest # Sử dụng image đã được build và push lên Docker Hub
    ports:
      - "9121:80"
    depends_on:
      - backend
    volumes:
      - ./client:/app # Đồng bộ mã nguồn từ ./client vào thư mục /app trong container
      - /app/node_modules # Tránh ghi đè node_modules trong container
    # environment:
    #   - CHOKIDAR_USEPOLLING=true # Kích hoạt hot reload

  backend:
    image: quangtt91/backend:check # Sử dụng image đã được build và push lên Docker Hub
    volumes:
      - ./uploads:/uploads # Bind mount thư mục uploads từ máy host vào container
      - ./server:/app # Đồng bộ mã nguồn từ ./backend vào /app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
