version: "3.8"
services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "9121:80"
    depends_on:
      - backend
    volumes:
      - ./client:/app # Đồng bộ mã nguồn từ ./client vào thư mục /app trong container
      - /app/node_modules # Tránh ghi đè node_modules trong container
    # environment:
    #   - CHOKIDAR_USEPOLLING=true # Kích hoạt hot reload

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/uploads # Bind mount thư mục uploads từ máy host vào container
      - ./backend:/app # Đồng bộ mã nguồn từ ./backend vào /app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
