name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Bước 1: Clone code từ repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Bước 2: Đăng nhập Docker Hub (nếu cần)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Bước 3: Build Docker images cho backend
      - name: Build backend Docker image
        run: |
          docker build --no-cache -t quangtt91/backend:https ./server

      # Bước 4: Build Docker images cho frontend
      - name: Build frontend Docker image
        run: |
          docker build --no-cache -t quangtt91/frontend:latest ./client

      # Bước 5: Push Docker images lên Docker Hub
      - name: Push backend image
        run: |
          docker push quangtt91/backend:https

      - name: Push frontend image
        run: |
          docker push quangtt91/frontend:latest

      # Bước 6: Cài đặt sshpass
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      # Bước 7: Deploy to remote server using SSH
      - name: Deploy to server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
        run: |
          # In thông tin debug
          echo "Starting deploy process..."

          # Chạy các lệnh SSH với sshpass
          sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR $SSH_USERNAME@$SSH_HOST <<EOF

          # Kiểm tra đường dẫn thư mục hiện tại
          echo "Current working directory:"
          pwd

          # Chuyển đến thư mục chứa docker-compose.yml
          cd /var/www/project2/deploy

          # Kiểm tra lại đường dẫn
          echo "After changing directory:"
          pwd

          # Kiểm tra xem file docker-compose.yml có tồn tại không
          if [ -f docker-compose.yml ]; then
            echo "docker-compose.yml file found."
          else
            echo "docker-compose.yml file not found!"
            exit 1
          fi

          # Kéo image mới từ Docker Hub
          docker pull quangtt91/backend:https
          docker pull quangtt91/frontend:latest
          # Dừng các container hiện tại
          docker-compose down
          # Khởi động lại các container từ docker-compose.yml
          docker-compose up -d
          EOF

      # Bước 8: Kiểm tra container đã chạy chưa
      # - name: Check container status
      #   run: |
      #     sshpass -p "$SSH_PASSWORD" ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR $SSH_USERNAME@$SSH_HOST <<EOF
      #     # Kiểm tra trạng thái các container đang chạy
      #     docker ps
      #     EOF
